pagination revamp
42-px/matrix-effector pull request #13
Opened 2021-04-05 10:42 UTC by holyslippers

Пока голый код, ридми не правил

2021-04-05 13:59 UTC, aanation requested changes

2021-04-05 13:59 UTC, aanation commented on src/init.ts
> +    filter: canLoad,
Мне кажется что для пагинации должен быть отдельный фильтр, который учитывает pending у эффектов load и самого эффекта пагинации (нельзя пагинировать когда уже есть пагинация или загрузка комнаты). 

То есть сделать сторы
$canLoad
$canPaginate 

Эти сторы нужно отдать наружу приложению, чтобы оно могло учитывать это в бизнес логике (сделать их публичными)

2021-04-05 13:59 UTC, aanation commented on src/init.ts
> +            roomId: roomId as any,
А зачем тут (и в аналгичных местах) каст типов?

2021-04-05 13:59 UTC, aanation commented on src/init.ts
> +    if (!timelineWindow) throw new TimelineWindowUndefined()
Мы вроде планировали тут сделать дозагрузку сообщений, чтобы четко выполнялся лимит

2021-04-05 14:16 UTC, qvlxty commented on src/init.ts
> +$roomId.on(initRoom, (_, { roomId }) => roomId)
На мой взгляд, стор лучше назвать $currentRoomId или, например, $workingRoomId, ткк это менее абстрактно и больше отображает скоуп того где он мог бы фигурировать

2021-04-05 14:46 UTC, holyslippers commented on src/state.ts
> +
да я подумал про это, но пока решил не реализовывать

2021-04-06 06:22 UTC, holyslippers commented on src/init.ts
> +            roomId: roomId as any,
Иначе тс логично ругается что эти параметры не <T>, а <T | null | undefined>. В действительности эффект с такими значениями не вызовется благодаря guard - но тс то это не объяснить.

2021-04-06 06:36 UTC, aanation commented on src/init.ts
> +            roomId: roomId as any,
Это я понимаю. Так мб кастить к string тогда просто? или еще лучше к Room['id'] если из комнаты тип айдишника можно достать. Меня именно каст к any смутил

2021-04-06 06:36 UTC, holyslippers commented on src/init.ts
> +            roomId: roomId as any,
оки, поправлю щас

2021-04-06 08:07 UTC, aanation requested changes

2021-04-06 08:07 UTC, aanation commented on src/public.ts
> +import { loadRoomFx } from "./private"
в public не разрешено импортить из private (это может вести к циклическим зависимостям)
В твом случае нужно
1. Обяъвить локлаьный приватный стор
```ts
const $loadRoomFxPending = matrixDomain.store(false)
```
2. в init.ts сделать так
```ts
import { loadRoomFx } from './private'
import { $loadRoomFxPending } from './public'

forward({
    from: loadRoomFx.pending,
    to: $loadRoomFxPending,
})
```

2021-04-06 08:07 UTC, aanation commented on src/init.ts
> +    .on(paginateBackwardFx.pending.updates, (_, value) => value)
Лучше просто зафорвардить эти сторы
```ts
forward({
   from: paginateForwardFx.pending,
   to: $paginateForwardPending,
})

forward({
   from: paginateBackwardFx.pending,
   to: $paginateBackwardPending,
})
```

2021-04-06 08:07 UTC, aanation commented on src/init.ts
> +    .on(paginateBackwardFx.pending.updates, (_, value) => value)
В этом случае у тебя в одном месте будет сгрупирована такая идентичная логика

```ts
forward({
    from: loadRoomFx.pending,
    to: $loadRoomFxPending,
})

forward({
   from: paginateForwardFx.pending,
   to: $paginateForwardPending,
})

forward({
   from: paginateBackwardFx.pending,
   to: $paginateBackwardPending,
})
```

2021-04-06 08:07 UTC, aanation commented on src/init.ts
> +    filter: $canPaginate,
Во, нормас! по красоте

2021-04-06 08:47 UTC, aanation requested changes

2021-04-06 08:47 UTC, aanation commented on src/init.ts
> +    .reset(onRoomReset)
Кажется, сюда можно просто засунуть .reset($currentRoomId)

2021-04-06 08:47 UTC, aanation commented on src/init.ts
> +    .reset(onRoomReset)
И тогда юнит onRoomReset больше не нужен кажется

2021-04-06 09:14 UTC, aanation approved these changes

2021-04-06 09:19 UTC, merged