centered property added
42-px/matrix-effector pull request #19
Opened 2021-04-16 14:05 UTC by qvlxty

- Добавлен параметр centered на событие loadRoom

2021-04-21 11:21 UTC, aanation approved these changes

2021-04-21 16:24 UTC, aanation approved these changes

2021-04-22 05:17 UTC, holyslippers commented
От себя добавлю что loadRestDataDirection было бы точнее и лаконичнее

2021-04-22 05:18 UTC, holyslippers commented on src/types.ts
> +  loadAdditionalDataDirection: 'BACKWARD' | 'FOWARD';
Атата, букву пропустил - не FOWARD, а FORWARD

2021-04-22 05:18 UTC, holyslippers commented on src/types.ts
> +  loadAdditionalDataDirection?: 'BACKWARD' | 'FOWARD';
Тоже самое, буква в литерале

2021-04-22 05:20 UTC, holyslippers commented
Надо еще добавить это в ридми

2021-04-22 05:25 UTC, holyslippers commented on src/init.ts
> +        if (loadAdditionalDataDirection === 'BACKWARD') {
Должны быть двойные кавычки

2021-04-22 05:25 UTC, holyslippers commented on src/init.ts
> +            loadAdditionalDataDirection = 'BACKWARD'
Должны быть двойные кавычки

2021-04-22 05:28 UTC, holyslippers commented on src/init.ts
> +        loadAdditionalDataDirection
Для чего это выражение "&& loadAdditionalDataDirection"? Оно же всегда будет true - либо дефолтное значение параметра, либо пользователь передаст свое значение параметра.

2021-04-22 05:28 UTC, holyslippers requested changes
Just small fixes

2021-04-22 07:40 UTC, qvlxty commented on src/init.ts
> +        loadAdditionalDataDirection
ага) забыл убрать когда ts для прошлой реализации подсказывал что переменная опциональная. Спасибо)

2021-04-22 08:18 UTC, holyslippers approved these changes

2021-04-22 08:18 UTC, merged