Room members
42-px/matrix-effector pull request #28
Opened 2021-06-18 08:17 UTC by holyslippers

Реактивный стор RoomMembers, который обновляется на разные события пользователя.

2021-06-18 08:21 UTC, qvlxty approved these changes
Нормас

2021-06-22 07:10 UTC, aanation requested changes

2021-06-22 07:15 UTC, aanation requested changes

2021-06-22 07:15 UTC, aanation commented on src/init.ts
> +    from: [$currentRoomId.updates],
Ладно, пусть не проверяется. Но скобки у массива можно убрать

2021-06-22 07:15 UTC, aanation commented on src/init.ts
> +    filter: $currentRoomId.map((roomId) => Boolean(roomId)),
Тут можно через clock и source написать, без сэмпла

2021-06-22 07:28 UTC, aanation approved these changes

2021-06-22 07:31 UTC, merged