UploadsUtils
42-px/matrix-effector pull request #29
Opened 2021-06-24 12:40 UTC by qvlxty

Добавил функцию-утилку , которая возвращает креды пользователя и путь до эндпойнта - данные, необходимые для отправки файлов через matrix rest api

2021-06-24 12:56 UTC, aanation approved these changes

2021-06-25 06:30 UTC, holyslippers requested changes
Мелочь

2021-06-25 06:30 UTC, holyslippers commented on package.json
> +  "version": "3.1.1",
Версию надо было бы поставить 3.2.0, т.к. это не багфикс.

2021-06-25 08:54 UTC, holyslippers approved these changes

2021-07-02 08:39 UTC, merged