add create room logic
42-px/matrix-effector pull request #40
Opened 2021-10-08 10:46 UTC by skyka13711

2021-10-11 07:05 UTC, holyslippers requested changes

2021-10-11 07:05 UTC, holyslippers commented on src/room/init.ts
> +    return client().joinRoom(roomId)
Нужно тоже мапать: возвращать RoomWithActivity (он в свою очередь считается из MappedRoom)

2021-10-11 07:05 UTC, holyslippers commented on src/room/public.ts
> +export const inviteUserFx = roomDomain.effect<InviteUserParams, Promise<void>, Error>()
Поправить типы: с Promise<void> на void. Ниже аналогично

2021-10-11 08:30 UTC, qvlxty requested changes
Паша уже показал на острые места

2021-10-15 06:49 UTC, holyslippers commented on src/app/init.ts
> +                newDirectRoom(room)
лучше переименовать в DirectRoomCreated

2021-10-15 06:49 UTC, holyslippers commented on src/app/init.ts
> +                newRoom(room)
аналогично RoomCreated

2021-10-15 06:51 UTC, holyslippers commented on src/app/init.ts
> +            const { joined_rooms } = await client().getJoinedRooms() as any
Здесь не надо сайд эффекты использовать: надо здесь дергать событие, на которое запускать эффект получения комнат

2021-10-15 06:57 UTC, holyslippers commented on src/utils.ts
> +export const setDirectRoom = (roomId: string) => {
Это асинхронный код, надо пофиксить типы

2021-10-15 07:50 UTC, aanation requested changes

2021-10-15 07:50 UTC, aanation commented on src/app/init.ts
> +            // @ts-ignore
А чем здесь tsignore обусловлен?

2021-10-15 07:50 UTC, aanation commented on src/app/init.ts
> +            const isDirect = room.currentState.getStateEvents("m.room.create" as EventType, undefined)[0]?.getContent()?.isDirect
Это скорее вопрос. А что нам обеспечивает наличие здесь m.room.create эвента? Раньше вроде бы его здесь не было и падало исключение

2021-10-15 07:50 UTC, aanation commented on src/room/init.ts
> +        initial_state: initialState.map((state) => ({
А что предполагается передавать в initialState с клиента?

2021-10-15 07:56 UTC, skyka13711 commented on src/app/init.ts
> +            // @ts-ignore
Метод getStateEvents принимает 2 параметра, второй опциональный, если он не нужен, то требуется передать undefined, но в типах сказано, что это обязательный параметр типа string

2021-10-15 07:57 UTC, skyka13711 commented on src/app/init.ts
> +            const isDirect = room.currentState.getStateEvents("m.room.create" as EventType, undefined)[0]?.getContent()?.isDirect
Исключение было из-за пустого memberShip. Вчера совсем глаз замылился. m.room.create Эвент заполняется при создании комнаты, потому он обязан быть, при вызове эвента Room

2021-10-15 09:33 UTC, qvlxty commented on src/app/init.ts
> +    ["Room", async (room: Room) => {
async remove

2021-10-15 09:34 UTC, qvlxty commented on src/mappers.ts
> +import { checkIsDirect, client } from "."
циклические зависимости

2021-10-15 09:47 UTC, holyslippers requested changes

2021-10-15 09:47 UTC, holyslippers commented on src/utils.ts
> +    // @ts-ignore
Ну не надо юзать ts-ignore - он будет распространяться ниже. Лучше заюзай
```
cl.getRoom(roomId)?.currentState
        .(getStateEvents("m.room.create") as any)[0]?.getContent()
```

2021-10-15 10:46 UTC, merged