Update matrix js sdk
42-px/matrix-effector pull request #49
Opened 2021-11-17 08:41 UTC by skyka13711

2021-11-17 08:57 UTC, qvlxty requested changes

2021-11-17 08:57 UTC, qvlxty commented on src/app/types.ts
> +import { CreateClientOptions } from "@/types";
;)))

2021-11-17 08:57 UTC, qvlxty commented on src/mappers.ts
> +    const matrixContent = event.getContent<MessageContent>()
го сразу return

2021-11-17 08:57 UTC, qvlxty commented on src/app/init.ts
> +logoutFx.use( async () => {
Посмотри что за типы у client().logout. Если logout возвращает что-то осмысленное, то можно без эвейта вернуть промис сразу наверх, чтобы любые разработчики могли управлять промисом выше

2021-11-17 08:57 UTC, qvlxty commented on src/room/init.ts
> +    await client().leave(roomId)
Если leave возвращает что-то полезное, что можно использовать наверху, и тебе не требуется свести возвращаемое значение эффекта к void, то лучше .use((roomId) => client().leave(roomId)) записать сразу

2021-11-17 21:41 UTC, aanation requested changes

2021-11-17 21:41 UTC, aanation commented on src/app/init.ts
> +    EventType,
ты не используешь EventType в этом модуле

2021-11-17 21:41 UTC, aanation commented on src/app/init.ts
>              ) as any)[0]?.getContent()?.isDirect
1. Тут вроде не нужно кастить типы, я убрал и у меня всё ок
```ts
const isDirect = (room.currentState
            .getStateEvents("m.room.create"))[0]?.getContent()?.isDirect
```

2. Метод getContent принимает дженерик от IContent, поэтому чтобы isDirect не был any можно сделать так
```ts
       // тип можно вынести в типы 
        type StateEventsContent = IContent & {
            isDirect?: boolean
        }

        const isDirect = (room.currentState
            .getStateEvents("m.room.create"))[0]?.getContent<StateEventsContent>()?.isDirect
```

2021-11-17 21:41 UTC, aanation commented on src/app/init.ts
> +import { updateMessages } from "@/room-messages/private"
Мы тут в приватный импорт залезли, надо бы этот эвент публичным сделать

2021-11-17 21:41 UTC, aanation commented on src/mappers.ts
> +} from "@/index"
Нельзя импортить из индекса, это верный путь к циклическим зависимостям

2021-11-17 21:41 UTC, aanation commented on src/room-messages/init.ts
> +    // True to hide the receipt from other users and homeservers. This property is unstable and may change in the future.
Всё в порядке, они его не юзают xD

![Screenshot from 2021-11-18 04-32-40](https://user-images.githubusercontent.com/32829122/142285845-280bdf41-6234-45da-91a9-14c118211f3c.png)

2021-11-17 21:41 UTC, aanation commented on src/room/init.ts
> +    // @TODO fix optional type
Сделай им PR плиз, у них там явно ошибка в сигнатуре. 
Потому что они его в коде проверяю
![Screenshot from 2021-11-18 04-36-45](https://user-images.githubusercontent.com/32829122/142286332-fd4ad9d0-0cdb-41e1-b008-f9e2f2a0dc47.png)
т

2021-11-17 21:41 UTC, aanation commented on src/room/init.ts
> +                membersCache[senderId] = room.getMember(senderId) as RoomMember
У нас точно не может быть в жизни кейсов когда матрикс нам не отдаст мембера который есть на самом деле?

2021-11-17 21:41 UTC, aanation commented on src/utils.ts
> +        ) as any)[0]?.getContent()
Тут вроде тоже кастить не надо

2021-11-25 18:53 UTC, aanation requested changes
В дополнение к предыдущему коменту, пройдись пожалуйста линтером по проекту. Кажется, у тебя в IDE не пашет eslint, в проекте есть места где табуляция некорректная и другие молчи

2021-11-25 18:53 UTC, aanation commented on src/room-messages/init.ts
>  import { paginateForwardFx } from "@/room-pagination/private"
Тут импорт из приватного модуля. Пройдись, пожалуйста, по всему matrix-effector и избавься от приватных импортов. 
Понимаю, что они возникли не здесь, и это дефект который проглядели, и этот маштабный PR хорошее место чтобы сделать это 

Кроме того, мне кажется что выделение отдельного модуля room-pagination не имеет смысла. Его использует только room-messages, а это верный признак того что это на самом деле одно и тоже. Предлагаю объединить их, переместив содержимое room-pagination в room-messages. Это избавит от части проблем с импортами из private

2021-11-26 08:48 UTC, aanation approved these changes

2021-11-26 08:48 UTC, merged