add getProfileInfoFx and up version
42-px/matrix-effector pull request #50
Opened 2021-11-23 05:37 UTC by skyka13711

2021-11-25 09:19 UTC, qvlxty approved these changes

2021-11-30 21:27 UTC, aanation requested changes

2021-11-30 21:27 UTC, aanation commented on src/room/init.ts
> +    effect: getRoomByIdFx
setRoomByIdFx - неудачный нейминг. Я понял что ты хочешь тут сделать (использовать getRoomByIdFx во внешнем мире без последствий, а эффектом setRoomByIdFx сеттерить внутри этой фичи).
Но из-за семантики понял это не сразу. 
Аттач чего-то set над чем то get выглядит очень странно

Предлагаю переименовать в setRoomByIdFx > getCurrentRoomFx

2021-11-30 21:27 UTC, aanation commented on src/utils.ts
> +    interlocutor?: string
interlocutor очень неочевидная конотация) Давай заменим на что то более типичное и понятное. Напрмер companion

2021-12-01 06:36 UTC, aanation approved these changes

2021-12-01 06:36 UTC, merged