add message isRead
42-px/matrix-effector pull request #53
Opened 2021-12-07 07:46 UTC by skyka13711

2021-12-07 07:54 UTC, qvlxty commented on src/mappers.ts
> +export const checkIsReadMyMessage = (
я бы назвал checkMessageSeen
IsRead немного сбивает столку (имхо)

2021-12-07 07:56 UTC, qvlxty commented on src/mappers.ts
> +            lastMessage.isRead = checkIsReadMyMessage(
Таже тема, может isRead -> seen?
На мой взгляд, более релевантное название

2021-12-07 17:36 UTC, aanation requested changes

2021-12-07 17:36 UTC, aanation commented on src/room-messages/init.ts
> +        throttleUpdateMessage,
Ты не импортируешь нигде за пределами room-messages этот эвент (throttleUpdateMessage), хотя он у тебя в public лежит. 
При этом для затротленных эвентов обычно не просто придумать норм название. Он по идее тебе не нужен же в public? Если нет то предлагаю его убрать из public а тут просто на месте применить throttle (только вынеси еще 800 в константу плиз):

```ts
guard({
    source: sample(
        [$currentRoomId, $timelineWindow],
        throttle({
            source: updateMessages,
            timeout: 800
        }),
        ([roomId, timelineWindow]) => ({
            timelineWindow: timelineWindow as TimelineWindow,
            roomId: roomId as string
        })
    ),
    filter: $timelineWindow.map(timelineWindow => Boolean(timelineWindow)),
    target: updateMessagesFx,
})
```

2021-12-07 17:36 UTC, aanation commented on src/room-messages/init.ts
> +    clock: debounceReadSelfMessage,
Здесь тоже предлагаю просто "на месте" заюзать debounce) 
Всю логику будет видно сразу и не нужно лезть вверх и смотреть что это за эвент

2021-12-07 17:36 UTC, aanation commented on src/mappers.ts
> +): boolean  => room.getJoinedMembers().some((member) => {
Эта функция - скорее утилка чем mapper. Давай переместим ее в utils

2021-12-08 20:51 UTC, aanation approved these changes

2021-12-08 20:51 UTC, merged