fix invite
42-px/matrix-effector pull request #54
Opened 2021-12-08 08:45 UTC by skyka13711

2021-12-15 09:09 UTC, qvlxty approved these changes

2021-12-19 09:07 UTC, aanation requested changes

2021-12-19 09:07 UTC, aanation commented on src/room/init.ts
> -    await client().invite(roomId, userId)
А зачем удалять старый эффект? Это breaking change на пустом месте, который сломает мобилку например если она юзает этот эффект. 

Мне кажется старый эффект следует оставить и добавить к нему новый

2021-12-19 09:07 UTC, aanation commented on src/room/init.ts
> -    getRoomMembersFx,
Ты тут эффект переименовал. Это точно того стоит? Это breaking change. Предлагаю оставить старое имя. Семантика всё равно норм будет: getRoomMembersFx -> getCurrentRoomMembersFx

2021-12-19 09:07 UTC, aanation commented on src/room/types.ts
> +    usersIds: string[]
Опять же ты меняешь апи. Я понимаю что тебе старый эффект не нужен. Но так как этот модуль библиотека, и ее помимо десктопа использует мобилка лучше оставить старый эффект с теми же типами и просто добавить новый

2021-12-19 09:36 UTC, skyka13711 commented on src/mappers.ts
> +                myPowerLevel >= powerLevelsContent.events[EventType.RoomName]
Да, сервер сетает туда дефолтные значения при создании комнаты

2021-12-19 09:37 UTC, skyka13711 commented on src/mappers.ts
> +
Евент добавляется сразу после создания комнаты с дефолт значениями

2021-12-19 17:33 UTC, aanation requested changes

2021-12-19 17:33 UTC, aanation commented on src/room/types.ts
> +    usersId: string
Тут переименовался параметр)

2021-12-19 17:52 UTC, aanation approved these changes

2021-12-20 04:04 UTC, merged